version: '2'
services:
    jhipstersample-app:
        image: jhipstersample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstersample-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterSample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersample-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersample-mongodb
